apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    system: "realworld"
    app: "backend"
spec:
  containers:
    - name: backend
      image: "eu.gcr.io/prefix-pontus-tf-prsuffix/devops-realworld-example-backend@sha256:0dae21e4ceb950f4ee2fc648568965d216e68af8d700c1c548ee517ef99c550e"
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
